apiVersion: v1
entries:
  kong:
  - apiVersion: v1
    appVersion: "2.7"
    created: "2022-02-23T19:25:52.565152-06:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.6.8
    description: The Cloud-Native Ingress and API-management
    digest: 4572dae5dd1672122bf8593b1d4969fdccac81c26a417e9b1fa23ac2ef89ed33
    home: https://konghq.com/
    icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
    maintainers:
    - email: harry@konghq.com
      name: hbagdi
    - email: traines@konghq.com
      name: rainest
    name: kong
    urls:
    - https://cghanapu.github.io/charts/charts/kong-2.7.0.tgz
    version: 2.7.0
generated: "2022-02-23T19:25:52.557162-06:00"
